name: Build and deploy website

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: actions/setup-node@v1
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: npm ci
      run: npm ci
    - name: npm run build
      run: npm run build
    - name: peaceiris/actions-gh-pages@v3
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build
